// Personelin hangi envanteri aldığı ve Teslim alan personel yazılmayacak çünkü users'de personalde ref verdiğimiz için bu iki bilgiyi otoman bir şekilde elde etmiş olacağız.

export const products = [
  {
    _id: 1,
    type: "Mouse",
    dateOfEntry: "3 Temmuz 2021",
    brand: "Razer",
    model: "km-03",
    serialNumber: 456952148,
    status: "Depoda",
    takenProductDate: "",
    submitterPersonal: "",
    returnProductDate: "",
  },
  {
    _id: 2,
    type: "Araba",
    dateOfEntry: "8 Temmuz 2021",
    brand: "Fiat",
    model: "Egea",
    serialNumber: 416252158,
    status: "Personelde",
    takenProductDate: "",
    submitterPersonal: "",
    returnProductDate: "",
  },
  {
    _id: 3,
    type: "Bilgisayar",
    dateOfEntry: "5 Temmuz 2021",
    brand: "Monster",
    model: "Mo5",
    serialNumber: 556942180,
    status: "Depoda",
    takenProductDate: "",
    submitterPersonal: "",
    returnProductDate: "",
  },
  {
    _id: 4,
    type: "Disk",
    dateOfEntry: "1 Temmuz 2021",
    brand: "Anoma",
    model: "Lomq",
    serialNumber: 426952548,
    status: "Ofiste",
    takenProductDate: "",
    submitterPersonal: "",
    returnProductDate: "",
  },
];
