export const users = [
  {
    _id: 1,
    name: "Metehan",
    surname: "Muradoglu",
    gender: "Erkek",
    birthDate: "3 Nisan 2003",
    identificationNumber: "16610014750",
    maritalStatus: false,
    registrationNumber: 1,
    graduationStatus: "Lise",
    unit: "İnsan Kaynaklari",
    Duty: "Personel alimi",
    isWorking: true,
    profilePhoto: "",
    username: "metebeli",
    password: "123",
    role: "IK",
  },
  {
    _id: 1,
    name: "Belinay",
    surname: "Muradoglu",
    gender: "Kadin",
    birthDate: "6 Temmuz 2010",
    identificationNumber: "15520014550",
    maritalStatus: false,
    registrationNumber: 2,
    graduationStatus: "Ortaokul",
    unit: "Arge",
    Duty: "Yönetmen",
    isWorking: true,
    profilePhoto: "",
    username: "belimete",
    password: "1234",
    role: "Envanter Yönetimi",
    inventory: [{}],
  },
  {
    _id: 1,
    name: "Admin Metehan",
    surname: "Muradoglu",
    gender: "Erkek",
    birthDate: "10 Temmuz 2010",
    identificationNumber: "15941154551",
    maritalStatus: false,
    registrationNumber: 3,
    graduationStatus: "Doktora",
    unit: "Yazilim Geliştirme",
    Duty: "Security",
    isWorking: true,
    profilePhoto: "",
    username: "metehanbelinay",
    password: "12345",
    role: "Admin",
  },
];
